"""
map_index_generator.py - Generate index and README files for map output folders

Creates:
  - README.txt in each subfolder listing available maps
  - index.html for browsing all PNG maps from a web browser
  - Quick reference guide

Usage
-----
    from map_index_generator import MapIndexGenerator
    gen = MapIndexGenerator()
    gen.generate_all()

    # Or generate specific parts:
    gen.generate_subfolder_readmes()
    gen.generate_html_index()
    gen.generate_quick_reference()
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, List, Optional

from map_output_manager import (
    MapOutputManager,
    BASE_OUTPUT_DIR,
    SUBFOLDER_DEFINITIONS,
    EXPECTED_FILES,
)


# ---------------------------------------------------------------------------
# Generator class
# ---------------------------------------------------------------------------

class MapIndexGenerator:
    """
    Generate index and README files for the organised map output structure.

    Parameters
    ----------
    base_dir : str
        Top-level output directory (default: ``map_outputs``).
    """

    def __init__(self, base_dir: str = BASE_OUTPUT_DIR) -> None:
        self.base_dir = Path(base_dir)
        self._mgr = MapOutputManager(base_dir)

    # ------------------------------------------------------------------
    # Per-subfolder README.txt
    # ------------------------------------------------------------------

    def generate_subfolder_readmes(self) -> List[str]:
        """
        Write a README.txt into each subfolder.

        Returns
        -------
        list of str
            Paths to generated README files.
        """
        self._mgr.create_all_folders()
        paths: List[str] = []

        for name, description in SUBFOLDER_DEFINITIONS.items():
            folder = self.base_dir / name
            existing = sorted(
                f.name for f in folder.iterdir()
                if f.is_file() and f.name not in {"README.txt", "index.html"}
            )
            expected = EXPECTED_FILES.get(name, [])

            lines = [
                "=" * 50,
                f"FOLDER: {name}/",
                "=" * 50,
                f"Description: {description}",
                "",
            ]

            if existing:
                lines += ["Files in this folder:", ""]
                for f in existing:
                    size_kb = (folder / f).stat().st_size // 1024
                    lines.append(f"  - {f}  ({size_kb} KB)")
            else:
                lines += [
                    "No files yet.",
                    "",
                    "Expected files:",
                ]
                for f in expected:
                    lines.append(f"  - {f}")

            lines += [
                "",
                "Naming convention: {type}_{dimension/region}_{suffix}.png",
                "",
                "To populate this folder, run:",
                "  python generate_all_maps_organized.py",
                "",
                "Generated by map_index_generator.py",
            ]

            readme_path = folder / "README.txt"
            readme_path.write_text("\n".join(lines), encoding="utf-8")
            print(f"README.txt written: {name}/")
            paths.append(str(readme_path))

        return paths

    # ------------------------------------------------------------------
    # HTML index
    # ------------------------------------------------------------------

    def generate_html_index(self) -> str:
        """
        Create index.html in map_outputs/ that displays thumbnails of all PNG maps.

        Returns
        -------
        str
            Path to the generated index.html.
        """
        self.base_dir.mkdir(parents=True, exist_ok=True)

        # Collect all PNG files across subfolders
        sections: Dict[str, List[str]] = {}
        for name in SUBFOLDER_DEFINITIONS:
            folder = self.base_dir / name
            if folder.is_dir():
                pngs = sorted(
                    f.name for f in folder.iterdir()
                    if f.suffix.lower() in {".png", ".gif"}
                )
                if pngs:
                    sections[name] = pngs

        # Build HTML
        section_html = ""
        for name, files in sections.items():
            description = SUBFOLDER_DEFINITIONS.get(name, "")
            items_html = "\n".join(
                f"""      <div class="card">
        <a href="{name}/{f}" target="_blank">
          <img src="{name}/{f}" alt="{f}" onerror="this.style.display='none'">
          <p>{f}</p>
        </a>
      </div>"""
                for f in files
            )
            section_html += f"""
  <section>
    <h2>{name.replace("_", " ").title()}</h2>
    <p class="desc">{description}</p>
    <div class="grid">
{items_html}
    </div>
  </section>
"""

        if not section_html:
            section_html = (
                "<p>No map files found yet. "
                "Run <code>generate_all_maps_organized.py</code> to produce maps.</p>"
            )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bangladesh Energy Poverty Maps</title>
  <style>
    * {{ box-sizing: border-box; }}
    body {{
      font-family: Arial, sans-serif;
      margin: 0; padding: 20px;
      background: #f5f6fa;
      color: #2c3e50;
    }}
    header {{
      background: #2c3e50;
      color: white;
      padding: 20px 30px;
      margin: -20px -20px 30px;
    }}
    header h1 {{ margin: 0; font-size: 1.8em; }}
    header p {{ margin: 5px 0 0; opacity: 0.8; }}
    section {{ margin-bottom: 40px; }}
    h2 {{
      color: #2c3e50;
      border-bottom: 2px solid #3498db;
      padding-bottom: 8px;
    }}
    .desc {{ color: #7f8c8d; font-size: 0.95em; margin: -8px 0 16px; }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: 16px;
    }}
    .card {{
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.1);
      overflow: hidden;
      transition: transform 0.2s;
    }}
    .card:hover {{ transform: translateY(-3px); }}
    .card a {{ display: block; text-decoration: none; color: inherit; }}
    .card img {{
      width: 100%;
      height: 160px;
      object-fit: cover;
      border-bottom: 1px solid #eee;
    }}
    .card p {{
      padding: 8px 10px;
      margin: 0;
      font-size: 0.78em;
      color: #555;
      word-break: break-all;
    }}
    footer {{
      margin-top: 40px;
      text-align: center;
      color: #aaa;
      font-size: 0.85em;
    }}
  </style>
</head>
<body>
  <header>
    <h1>🗺️ Bangladesh Energy Poverty Index – Map Gallery</h1>
    <p>Multidimensional Energy Poverty Index (MEPI) – Upazila Level Analysis</p>
  </header>
{section_html}
  <footer>
    <p>Generated by map_index_generator.py &nbsp;|&nbsp;
       Bangladesh Energy Poverty Mapping Project</p>
  </footer>
</body>
</html>
"""
        index_path = self.base_dir / "index.html"
        index_path.write_text(html, encoding="utf-8")
        print(f"HTML index written: {index_path}")
        return str(index_path)

    # ------------------------------------------------------------------
    # Quick reference guide
    # ------------------------------------------------------------------

    def generate_quick_reference(self) -> str:
        """
        Write a plain-text quick reference guide to map_outputs/QUICK_REFERENCE.txt.

        Returns
        -------
        str
        """
        self.base_dir.mkdir(parents=True, exist_ok=True)

        lines = [
            "QUICK REFERENCE – ENERGY POVERTY MAP OUTPUTS",
            "=" * 52,
            "",
            "FOLDER STRUCTURE",
            "-" * 52,
        ]

        for name, desc in SUBFOLDER_DEFINITIONS.items():
            lines.append(f"  map_outputs/{name}/")
            lines.append(f"    {desc}")
            for f in EXPECTED_FILES.get(name, [])[:3]:
                lines.append(f"    ├── {f}")
            lines.append("")

        lines += [
            "NAMING CONVENTION",
            "-" * 52,
            "  {type}_{dimension/region}_{suffix}.png",
            "",
            "  Examples:",
            "    mepi_spatial_map.png           → spatial_maps/",
            "    dimension_availability_map.png  → spatial_maps/",
            "    coastal_analysis_map.png        → regional_maps/",
            "    temporal_2021_comparison.png    → temporal_maps/",
            "    hotspot_clusters.png            → hotspot_maps/",
            "    top10_most_poor.png             → analysis_maps/",
            "    interactive_map.html            → interactive_maps/",
            "",
            "SCRIPTS",
            "-" * 52,
            "  setup_folder_structure.py        Create folder hierarchy (run once)",
            "  generate_all_maps_organized.py   Generate + organise all maps",
            "  map_organizer.py                 Sort unsorted PNGs into subfolders",
            "  map_index_generator.py           Regenerate README + index.html",
            "",
            "QUICK START",
            "-" * 52,
            "  python setup_folder_structure.py",
            "  python generate_all_maps_organized.py",
            "",
            "Generated by map_index_generator.py",
        ]

        ref_path = self.base_dir / "QUICK_REFERENCE.txt"
        ref_path.write_text("\n".join(lines), encoding="utf-8")
        print(f"Quick reference written: {ref_path}")
        return str(ref_path)

    # ------------------------------------------------------------------
    # Master method
    # ------------------------------------------------------------------

    def generate_all(self) -> Dict[str, str]:
        """
        Generate all index / README files.

        Returns
        -------
        dict
            Mapping of file type → path.
        """
        readme_paths = self.generate_subfolder_readmes()
        html_path = self.generate_html_index()
        ref_path = self.generate_quick_reference()

        return {
            "readmes": readme_paths,
            "index_html": html_path,
            "quick_reference": ref_path,
        }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import sys

    base = sys.argv[1] if len(sys.argv) > 1 else BASE_OUTPUT_DIR
    gen = MapIndexGenerator(base_dir=base)
    results = gen.generate_all()
    print(f"\nGenerated {len(results['readmes'])} README files, index.html, and quick reference.")
