"""
map_index_and_readme.py - Generate index.html and README files for external folder

Creates documentation files for the external map output directory:
  - README.txt in the main external folder
  - README.txt in each subfolder
  - index.html for browsing all maps in a web browser

Usage
-----
    python map_index_and_readme.py
    python map_index_and_readme.py --output-dir /custom/path/
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from external_folder_manager import (
    ExternalFolderManager,
    SUBFOLDER_DESCRIPTIONS,
    EXPECTED_FILES,
    ensure_external_folders,
)
from map_config_external import EXTERNAL_OUTPUT_BASE


# ---------------------------------------------------------------------------
# Documentation generator
# ---------------------------------------------------------------------------

class ExternalMapDocGenerator:
    """
    Generate README and index files for the external map output folder.

    Parameters
    ----------
    base_dir : str, optional
        External output root (defaults to EXTERNAL_OUTPUT_BASE).
    """

    def __init__(self, base_dir: Optional[str] = None) -> None:
        self._mgr = ensure_external_folders(base_dir)
        self.base_dir = self._mgr.base_dir

    # ------------------------------------------------------------------
    # Per-subfolder README.txt
    # ------------------------------------------------------------------

    def generate_subfolder_readmes(self) -> List[str]:
        """Write a README.txt into each subfolder."""
        paths: List[str] = []

        for name, description in SUBFOLDER_DESCRIPTIONS.items():
            folder = self.base_dir / name
            folder.mkdir(parents=True, exist_ok=True)

            existing = sorted(
                f.name for f in folder.iterdir()
                if f.is_file() and f.name not in {"README.txt", "index.html"}
            )
            expected = EXPECTED_FILES.get(name, [])

            lines = [
                "=" * 50,
                f"FOLDER: {name}/",
                "=" * 50,
                f"Description: {description}",
                "",
            ]

            if existing:
                lines += ["Files in this folder:", ""]
                for f in existing:
                    size_kb = (folder / f).stat().st_size // 1024
                    lines.append(f"  - {f}  ({size_kb} KB)")
            else:
                lines += [
                    "No files yet.",
                    "",
                    "Expected files:",
                ]
                for f in expected:
                    lines.append(f"  - {f}")

            lines += [
                "",
                "Naming convention: {type}_{dimension/region}_{suffix}.png",
                "",
                "To populate this folder, run:",
                "  python generate_all_maps.py",
                "",
                f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                "Bangladesh Energy Poverty Mapping Project",
            ]

            readme_path = folder / "README.txt"
            readme_path.write_text("\n".join(lines), encoding="utf-8")
            print(f"  README.txt written: {name}/")
            paths.append(str(readme_path))

        return paths

    # ------------------------------------------------------------------
    # Main folder README.txt
    # ------------------------------------------------------------------

    def generate_main_readme(self) -> str:
        """Write README.txt in the main external output folder."""
        self.base_dir.mkdir(parents=True, exist_ok=True)
        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines = [
            "=" * 60,
            "BANGLADESH ENERGY POVERTY INDEX – MAP OUTPUTS",
            "=" * 60,
            "",
            "This folder contains all Energy Poverty Index (MEPI) maps",
            "generated by the Bangladesh Energy Poverty Mapping project.",
            "",
            f"Generated: {now}",
            f"Location : {self.base_dir}",
            "",
            "FOLDER STRUCTURE",
            "-" * 60,
        ]

        for name, description in SUBFOLDER_DESCRIPTIONS.items():
            lines.append(f"  {name}/")
            lines.append(f"    {description}")
            for f in EXPECTED_FILES.get(name, [])[:3]:
                lines.append(f"    ├── {f}")
            lines.append("")

        lines += [
            "BROWSING THE MAPS",
            "-" * 60,
            "  Open index.html in any web browser to see a thumbnail gallery",
            "  of all available maps.",
            "",
            "  Interactive HTML maps are in interactive_maps/ – open them",
            "  in a browser to explore MEPI data on an interactive map.",
            "",
            "REGENERATING MAPS",
            "-" * 60,
            "  Run the following commands from the repository directory:",
            "",
            "  # Generate all maps (one command):",
            "  python generate_all_maps.py",
            "",
            "  # Generate specific map types:",
            "  python spatial_maps_external.py",
            "  python regional_maps_external.py",
            "  python temporal_maps_external.py",
            "  python hotspot_maps_external.py",
            "  python analysis_maps_external.py",
            "  python interactive_maps_external.py",
            "",
            "CONFIGURATION",
            "-" * 60,
            "  Output directory can be changed in map_config_external.py or",
            "  by setting the MEPI_MAP_OUTPUT_DIR environment variable.",
            "",
            "Bangladesh Energy Poverty Mapping Project",
        ]

        readme_path = self.base_dir / "README.txt"
        readme_path.write_text("\n".join(lines), encoding="utf-8")
        print(f"  README.txt written: {self.base_dir}")
        return str(readme_path)

    # ------------------------------------------------------------------
    # index.html thumbnail gallery
    # ------------------------------------------------------------------

    def generate_html_index(self) -> str:
        """Create index.html displaying thumbnails of all PNG/GIF maps."""
        self.base_dir.mkdir(parents=True, exist_ok=True)

        sections: Dict[str, List[str]] = {}
        for name in SUBFOLDER_DESCRIPTIONS:
            folder = self.base_dir / name
            if folder.is_dir():
                pngs = sorted(
                    f.name for f in folder.iterdir()
                    if f.suffix.lower() in {".png", ".gif"}
                )
                if pngs:
                    sections[name] = pngs

        # HTML sections for interactive maps (link only, no thumbnail)
        html_sections: Dict[str, List[str]] = {}
        interactive_folder = self.base_dir / "interactive_maps"
        if interactive_folder.is_dir():
            htmls = sorted(
                f.name for f in interactive_folder.iterdir()
                if f.suffix.lower() == ".html"
            )
            if htmls:
                html_sections["interactive_maps"] = htmls

        section_html = ""

        for name, files in sections.items():
            description = SUBFOLDER_DESCRIPTIONS.get(name, "")
            items_html = "\n".join(
                f"""      <div class="card">
        <a href="{name}/{f}" target="_blank">
          <img src="{name}/{f}" alt="{f}" loading="lazy"
               onerror="this.style.display='none'">
          <p>{f}</p>
        </a>
      </div>"""
                for f in files
            )
            section_html += f"""
  <section id="{name}">
    <h2>{name.replace("_", " ").title()}</h2>
    <p class="desc">{description}</p>
    <div class="grid">
{items_html}
    </div>
  </section>
"""

        # Interactive maps section (links only)
        for name, files in html_sections.items():
            if name not in sections:
                description = SUBFOLDER_DESCRIPTIONS.get(name, "")
                links_html = "\n".join(
                    f'      <li><a href="{name}/{f}" target="_blank">🗺️ {f}</a></li>'
                    for f in files
                )
                section_html += f"""
  <section id="{name}">
    <h2>{name.replace("_", " ").title()}</h2>
    <p class="desc">{description}</p>
    <ul class="link-list">
{links_html}
    </ul>
  </section>
"""

        if not section_html:
            section_html = (
                "<p style='padding:20px; color:#999;'>No map files found yet. "
                "Run <code>python generate_all_maps.py</code> to produce maps.</p>"
            )

        now = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Build navigation links as a separate variable for clarity
        nav_section_names = list(sections.keys()) + [
            name for name in html_sections.keys() if name not in sections
        ]
        nav_links = "".join(
            f'<a href="#{name}">{name.replace("_", " ").title()}</a>'
            for name in nav_section_names
        )

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bangladesh Energy Poverty Maps</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: Arial, Helvetica, sans-serif;
      background: #f5f6fa;
      color: #2c3e50;
      padding: 20px;
    }}
    header {{
      background: linear-gradient(135deg, #2c3e50, #3498db);
      color: white;
      padding: 24px 30px;
      margin: -20px -20px 30px;
      border-radius: 0 0 12px 12px;
    }}
    header h1 {{ font-size: 1.8em; margin-bottom: 6px; }}
    header p {{ opacity: 0.85; font-size: 0.95em; }}
    nav {{
      background: white;
      padding: 12px 20px;
      border-radius: 8px;
      margin-bottom: 24px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.08);
    }}
    nav a {{
      margin-right: 16px;
      color: #3498db;
      text-decoration: none;
      font-size: 0.9em;
    }}
    nav a:hover {{ text-decoration: underline; }}
    section {{ margin-bottom: 40px; }}
    h2 {{
      font-size: 1.3em;
      color: #2c3e50;
      border-bottom: 2px solid #3498db;
      padding-bottom: 8px;
      margin-bottom: 6px;
    }}
    .desc {{ color: #7f8c8d; font-size: 0.92em; margin-bottom: 14px; }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(210px, 1fr));
      gap: 14px;
    }}
    .card {{
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 6px rgba(0,0,0,0.1);
      overflow: hidden;
      transition: transform 0.15s, box-shadow 0.15s;
    }}
    .card:hover {{ transform: translateY(-3px); box-shadow: 0 4px 12px rgba(0,0,0,0.15); }}
    .card a {{ display: block; text-decoration: none; color: inherit; }}
    .card img {{
      width: 100%;
      height: 150px;
      object-fit: cover;
      border-bottom: 1px solid #eee;
      background: #f0f0f0;
    }}
    .card p {{
      padding: 7px 10px;
      font-size: 0.75em;
      color: #666;
      word-break: break-all;
    }}
    .link-list {{ list-style: none; padding: 0; }}
    .link-list li {{
      background: white;
      margin-bottom: 8px;
      border-radius: 6px;
      box-shadow: 0 1px 4px rgba(0,0,0,0.08);
    }}
    .link-list li a {{
      display: block;
      padding: 10px 16px;
      color: #3498db;
      text-decoration: none;
      font-size: 0.95em;
    }}
    .link-list li a:hover {{ background: #eaf4fd; }}
    footer {{
      margin-top: 50px;
      text-align: center;
      color: #aaa;
      font-size: 0.82em;
      padding-bottom: 20px;
    }}
  </style>
</head>
<body>
  <header>
    <h1>🗺️ Bangladesh Energy Poverty Index – Map Gallery</h1>
    <p>Multidimensional Energy Poverty Index (MEPI) – Upazila Level Analysis
       &nbsp;|&nbsp; Generated: {now}</p>
  </header>
  <nav>
    <strong>Jump to:</strong>
    {nav_links}
  </nav>
{section_html}
  <footer>
    <p>Generated by map_index_and_readme.py &nbsp;|&nbsp;
       Bangladesh Energy Poverty Mapping Project &nbsp;|&nbsp;
       {now}</p>
  </footer>
</body>
</html>
"""
        index_path = self.base_dir / "index.html"
        index_path.write_text(html, encoding="utf-8")
        print(f"  index.html written: {self.base_dir}")
        return str(index_path)

    # ------------------------------------------------------------------
    # Master method
    # ------------------------------------------------------------------

    def generate_all(self) -> Dict[str, object]:
        """
        Generate all documentation files.

        Returns
        -------
        dict with keys: main_readme, subfolder_readmes, index_html
        """
        print("\n[Docs] Generating README and index files ...")
        main_readme = self.generate_main_readme()
        subfolder_readmes = self.generate_subfolder_readmes()
        index_html = self.generate_html_index()

        return {
            "main_readme":       main_readme,
            "subfolder_readmes": subfolder_readmes,
            "index_html":        index_html,
        }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate index.html and README files for external map folder."
    )
    parser.add_argument(
        "--output-dir", default=EXTERNAL_OUTPUT_BASE,
        help=f"External output base directory (default: {EXTERNAL_OUTPUT_BASE}).",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("MAP INDEX & README GENERATOR – EXTERNAL FOLDER")
    print("=" * 60)

    gen = ExternalMapDocGenerator(base_dir=args.output_dir)
    result = gen.generate_all()

    n_readmes = 1 + len(result["subfolder_readmes"])
    print(f"\n✅ {n_readmes} README file(s) + index.html created in:")
    print(f"   {gen.base_dir}")
    print(f"\n   Browse: {result['index_html']}")


if __name__ == "__main__":
    main()
