"""
report_config.py - Configuration settings for the MEPI report generation pipeline.

Centralises all user-adjustable parameters so that every other report-generation
module reads from a single source of truth.
"""

import os
from datetime import datetime

# =============================================================================
# REPORT METADATA
# =============================================================================

REPORT_TITLE = "Multidimensional Energy Poverty Index (MEPI) in Bangladesh"
REPORT_SUBTITLE = "A Comprehensive Spatial and Dimensional Analysis"
REPORT_AUTHORS = ["Md. Iqbal Hossain"]
REPORT_ORGANIZATION = "Energy Poverty Research Group"
REPORT_YEAR = str(datetime.now().year)
REPORT_DATE = datetime.now().strftime("%B %Y")
REPORT_VERSION = "1.0"
REPORT_DOI = "10.xxxx/mepi-bangladesh-2026"

# =============================================================================
# OUTPUT PATHS
# =============================================================================

# Output directory for the final reports
REPORT_OUTPUT_DIR = os.path.expanduser("~/energy_poverty_reports")

# Folder within the report output directory for extracted figures and tables
FIGURES_SUBFOLDER = "figures_and_tables"

# Spatial maps source directory (PNG files generated by spatial mapping scripts)
SPATIAL_MAPS_DIR = os.path.expanduser("~/spatial_maps_png")

# Generated charts directory (created by chart_graph_generator.py)
CHARTS_OUTPUT_DIR = os.path.join(REPORT_OUTPUT_DIR, "charts")

# =============================================================================
# CITATION STYLE
# =============================================================================

# Supported values: "APA", "Harvard", "IEEE"
CITATION_STYLE = "APA"

# =============================================================================
# TYPOGRAPHY AND STYLING
# =============================================================================

# Font family used for headings and body in PDF output
FONT_FAMILY = "Helvetica"

# Font sizes (points)
FONT_SIZE_TITLE = 24
FONT_SIZE_CHAPTER_HEADING = 18
FONT_SIZE_SECTION_HEADING = 14
FONT_SIZE_SUBSECTION_HEADING = 12
FONT_SIZE_BODY = 11
FONT_SIZE_CAPTION = 9
FONT_SIZE_FOOTER = 9
FONT_SIZE_TABLE_HEADER = 10
FONT_SIZE_TABLE_BODY = 9

# Page margins (in points; 72 points = 1 inch)
PAGE_MARGIN_TOP = 72
PAGE_MARGIN_BOTTOM = 72
PAGE_MARGIN_LEFT = 72
PAGE_MARGIN_RIGHT = 72

# Line spacing multiplier for body text
LINE_SPACING = 1.4

# =============================================================================
# COLOUR SCHEME
# =============================================================================

COLOR_PRIMARY = "#1F4E79"       # Deep navy – headings, table headers
COLOR_SECONDARY = "#2E75B6"     # Mid-blue – subheadings
COLOR_ACCENT = "#ED7D31"        # Orange – call-outs, highlights
COLOR_BACKGROUND_LIGHT = "#D6E4F0"   # Light blue – alternate table rows
COLOR_LIGHT_HEX = "#D6E4F0"         # Alias used by builders
COLOR_TABLE_HEADER_TEXT = "#FFFFFF"  # White – table header text

# Poverty-category highlight colours (HTML hex)
COLOR_SEVERE = "#FFC7CE"        # Red tint
COLOR_MODERATE = "#FFEB9C"      # Yellow tint
COLOR_NON_POOR = "#C6EFCE"      # Green tint

# =============================================================================
# IMAGE / FIGURE SETTINGS
# =============================================================================

# DPI for embedded images in PDF (300 = publication quality)
IMAGE_DPI = 300

# Maximum width / height for embedded figures (in points; 1 pt = 1/72 inch)
FIGURE_MAX_WIDTH = 468    # ~ 6.5 inches
FIGURE_MAX_HEIGHT = 360   # ~ 5 inches

# Caption prefix strings
FIGURE_CAPTION_PREFIX = "Figure"
TABLE_CAPTION_PREFIX = "Table"

# =============================================================================
# OUTPUT FORMAT FLAGS
# =============================================================================

GENERATE_PDF = True
GENERATE_DOCX = True
GENERATE_SUMMARY_TXT = True
