"""
updated_interactive_folium_maps.py - Interactive HTML maps saved to organised folders

Extends :class:`InteractiveMapper` to route outputs to the organised directory
structure, generate a README for the interactive_maps/ subfolder, and create a
simple index.html linking all maps.

Usage
-----
    from updated_interactive_folium_maps import OrganisedInteractiveMapper
    mapper = OrganisedInteractiveMapper(mepi_df)
    mapper.create_all_maps()
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import List, Optional

from interactive_folium_maps import InteractiveMapper
from map_output_manager import MapOutputManager, BASE_OUTPUT_DIR


class OrganisedInteractiveMapper(InteractiveMapper):
    """
    Extension of :class:`InteractiveMapper` that saves all HTML maps to the
    ``interactive_maps/`` subfolder and generates supporting files.

    Parameters
    ----------
    mepi_df : pd.DataFrame
    base_dir : str
        Top-level output directory (default: ``map_outputs``).
    shapefile_path : str, optional
    name_col : str
    """

    def __init__(
        self,
        mepi_df,
        base_dir: str = BASE_OUTPUT_DIR,
        shapefile_path: Optional[str] = None,
        name_col: str = "upazila_name",
    ) -> None:
        super().__init__(
            mepi_df,
            shapefile_path=shapefile_path,
            name_col=name_col,
        )
        self._mgr = MapOutputManager(base_dir)
        self._mgr.create_all_folders()

    # ------------------------------------------------------------------
    # Path helpers
    # ------------------------------------------------------------------

    def _html_path(self, filename: str) -> str:
        return self._mgr.get_path("interactive_maps", filename)

    # ------------------------------------------------------------------
    # Overridden public methods
    # ------------------------------------------------------------------

    def create_mepi_map(
        self,
        output_path: Optional[str] = None,
    ) -> str:
        """Save main MEPI map to interactive_maps/interactive_map.html."""
        if output_path is None:
            output_path = self._html_path("interactive_map.html")
        return super().create_mepi_map(output_path=output_path)

    def create_dimension_maps(
        self,
        output_dir: Optional[str] = None,
    ) -> List[str]:
        """Save dimension HTML maps to interactive_maps/."""
        if output_dir is None:
            output_dir = self._mgr.get_subfolder_path("interactive_maps")
        return super().create_dimension_maps(output_dir=output_dir)

    def create_all_maps(self, output_dir: Optional[str] = None) -> List[str]:
        """
        Create all interactive maps and generate README + index.

        Returns
        -------
        list of str
        """
        paths: List[str] = []
        paths.append(self.create_mepi_map())
        paths.extend(self.create_dimension_maps())
        self.generate_readme()
        self.create_index_html(paths)
        return paths

    # ------------------------------------------------------------------
    # README and index
    # ------------------------------------------------------------------

    def generate_readme(self) -> str:
        """Write README_interactive_maps.txt into interactive_maps/."""
        output_path = self._html_path("README_interactive_maps.txt")
        content = """README - Interactive Maps
========================

This folder contains interactive HTML maps for the Bangladesh MEPI project.
Open any .html file in a modern web browser – no installation required.

Files
-----
  interactive_map.html           Main MEPI overview (all upazilas)
  interactive_availability_map.html  Availability dimension
  interactive_reliability_map.html   Reliability dimension
  interactive_adequacy_map.html      Adequacy dimension
  interactive_quality_map.html       Quality dimension
  interactive_affordability_map.html Affordability dimension
  index.html                     Browse all maps from one page

Features
--------
  • Click any upazila for a detailed popup with all dimension scores
  • Hover for a quick tooltip
  • Toggle layers via the Layer Control panel (top-right)
  • Switch between Street / Satellite / Dark basemaps
  • Fullscreen button available

Requirements
------------
  An active internet connection is needed for the basemap tiles.

Generated by updated_interactive_folium_maps.py
"""
        Path(output_path).write_text(content, encoding="utf-8")
        print(f"Saved: {output_path}")
        return output_path

    def create_index_html(self, map_paths: List[str]) -> str:
        """
        Create an index.html that links to every interactive HTML map.

        Parameters
        ----------
        map_paths : list of str
            Absolute paths to the HTML map files.

        Returns
        -------
        str
            Path to the generated index.html.
        """
        interactive_dir = Path(self._mgr.get_subfolder_path("interactive_maps"))
        index_path = interactive_dir / "index.html"

        html_files = sorted(
            p for p in map_paths
            if p.endswith(".html") and os.path.basename(p) != "index.html"
        )

        # Build list items (relative links)
        items = []
        for p in html_files:
            name = os.path.basename(p)
            label = (
                name.replace("interactive_", "")
                    .replace("_map.html", "")
                    .replace("_", " ")
                    .title()
            )
            items.append(f'    <li><a href="{name}" target="_blank">{label} Map</a></li>')

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bangladesh Energy Poverty Maps – Index</title>
  <style>
    body {{ font-family: Arial, sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; }}
    h1 {{ color: #2c3e50; }}
    h2 {{ color: #34495e; margin-top: 30px; }}
    ul {{ line-height: 2; }}
    a {{ color: #2980b9; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .note {{ color: #7f8c8d; font-size: 0.9em; }}
  </style>
</head>
<body>
  <h1>Bangladesh Energy Poverty Index – Interactive Maps</h1>
  <p class="note">
    Click a map to open it in a new browser tab.  All maps are self-contained HTML files
    that require an internet connection for the basemap tiles.
  </p>
  <h2>Available Maps</h2>
  <ul>
{chr(10).join(items)}
  </ul>
  <hr>
  <p class="note">Generated by updated_interactive_folium_maps.py</p>
</body>
</html>
"""
        index_path.write_text(html_content, encoding="utf-8")
        print(f"Saved: {index_path}")
        return str(index_path)
